schema_version = "1.0.0"

id = "easeit"
version = "0.9.0"
name = "Easeit"
tagline = "Quickly apply easing presets to animation keyframes"
maintainer = "Andy Cuccaro"
type = "add-on"

website = "https://github.com/andycuccaro/easeit-addon"

tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later",]